alias awg-private-sftp='sshpass -f ~/.ssh/awg-sftp.pwd sftp awg-private-sftp'
alias awg-public-sftp='sshpass -f ~/.ssh/awg-sftp.pwd sftp awg-public-sftp'
alias bml='borg mount ::$(borg list --short --last 1) ~/mount'
alias bubog='brew update && brew outdated --greedy'
alias bugbcp='bugbc --prune=all'
alias cat='bat -p'
alias cpac="grep antizapret $HOME/pac | tr -d '\n' | clipcopy"
alias ffmpeg='ffmpeg -hide_banner'
alias ffplay='ffplay -hide_banner'
alias ffprobe='ffprobe -hide_banner'
alias gdl=gallery-dl
alias gdlb='gallery-dl --cookies-from-browser brave'
alias gdlbd='gallery-dl --cookies-from-browser brave -d.'
alias gdlbD='gallery-dl --cookies-from-browser brave -D.'
alias gdld='gallery-dl -d.'
alias gdlD='gallery-dl -D.'
alias gdls='gallery-dl --cookies-from-browser safari'
alias ghw='gh repo view --web'
alias icat='kitten icat'
alias kd='kitten diff'
alias kgd='git difftool --no-symlinks --dir-diff'
alias ks='kitten ssh'
alias ktd='kitten transfer --confirm-paths --transmit-deltas --direction=download'
alias ktu='kitten transfer --confirm-paths --transmit-deltas --direction=upload'
alias ls=lsd
alias lspdf='mdls -name kMDItemFSName -name kMDItemNumberOfPages *.pdf(n) | cut -d= -f 2 | paste - -'
alias lspdfs='mdls -name kMDItemFSName -name kMDItemNumberOfPages *.pdf(n) | grep NumberOfPages | cut -d" " -f3 | paste -s -d+ - | bc'
alias mactop='sudo mactop'
alias rm='rm -I'
alias tailscale='/Applications/Tailscale.app/Contents/MacOS/Tailscale'
alias tjd='to_jxl ~/Downloads'
alias tjx='to_jxl ~/Export'
alias watch=viddy
alias yt-dlp='yt-dlp --downloader aria2c'
alias yt-dlp_sb='yt-dlp --downloader aria2c --legacy-server-connect'
alias yta='yt-dlp -f m4a'
