export EDITOR=nvim
export VISUAL=nvim
export GPG_TTY=$(tty)
export LC_ALL=ru_RU.UTF-8
export MONO_GAC_PREFIX="/opt/homebrew"
export RESEND_API_KEY=$(security find-generic-password -a RESEND_API_KEY -s resend.com -w)
export HISTIGNORE='*sudo -S*'
XDG_DATA_DIRS+=/opt/homebrew/share
export HOMEBREW_NO_ENV_HINTS=true
